### PR TITLE
Cover lint #15

### LINKED ISSUE #15: use code coverage and code linting
Add to `.travis.yml`
```yaml
r_binary_packages:
  - jimhester/lintr
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
```

Exec in `R`
```r
usethis::use_coverage("codecov")
usethis::use_build_ignore(".lintr")

lintr::lint_package() %>% 
  as.data.frame %>% 
  dplyr::group_by(linter) %>% 
  dplyr::tally(sort = TRUE) %$% 
  sprintf(
    "linters: with_defaults(\n    %s\n    NULL\n  )\n", 
    paste0(linter, " = NULL, # ", n, collapse = "\n    ")
  ) %>% 
  cat(file = ".lintr")
```

* Remove the packages from `Description`'s `Suggests`.
* Adjust the lint to allow for lines up to 100 characters.  (link: https://github.com/jimhester/lintr#project-configuration)

```r
lintr::lint_package(path = '.', relative_path = TRUE, with_defaults(line_length_linter(100)))
```
* Add the code coverage badge to the readme

### PR DESCRIPTION
**Pull request by chendaniely**
Fixes #15 

- [x] Remove the packages from Description's Suggests.
- [x] Adjust the lint to allow for lines up to 100 characters. (link: https://github.com/jimhester/lintr#project-configuration)
- [x] Add the code coverage badge to the readme (already there)

### CODE REVIEW

**Comment by chendaniely** [comment]
@schloerke any insight as to why the lintr-bot isn't working anymore?
Is the `.lintr` file specified incorrectly?

```
linters: with_defaults(
    line_length_linter = line_length_linter(100)
)
```

I've also tried it with 

```
linters: with_defaults(
    line_length_linter(100)
)
```

**Comment by chendaniely** [comment]
@schloerke is there anything else that needs to be done for this PR? should I turn off all the linters except for line width?

**Comment by schloerke** [comment]
@chendaniely Does anything appear on your local machine when you `lint::lint_package()`? It still looks like there is a bunch of issues.  (Or does your local machine output not agree with the github comment?)

> should I turn off all linters?

Only adjust the line width linter.  Otherwise all remaining linters _should_ be enabled. It's fine to keep `object_usage` disabled for now.

**Comment by chendaniely** [comment]
ALL PASS!

**Pull request merged**
